DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NUMERO VARCHAR(50) NOT NULL,
   NOMBRE VARCHAR(100) NOT NULL,
   APELLIDO VARCHAR(100) NOT NULL
);

-- test --

INSERT INTO ODONTOLOGOS (NUMERO, NOMBRE, APELLIDO) VALUES('12345', 'MARIA', 'JIMENEZ');

INSERT INTO ODONTOLOGOS (NUMERO, NOMBRE, APELLIDO) VALUES('12345', 'ANA', 'RODRIGUEZ');

INSERT INTO ODONTOLOGOS (NUMERO, NOMBRE, APELLIDO) VALUES('12345', 'PABLO', 'GONZALEZ');